### ISSUE TITLE
Which method should be traced to generate `examples`?

### ISSUE THREAD

**Issue by shioimm** [yhirano55/trace_location#14]
@yhirano55
I’d like you to tell me how did you generate files in `examples/`.
Because I’m working on new generator, for html, and it seems like that should be add new examples generated with this new file extension in `examples/`.

Now there are 5 kinds of files in examples, but I couldn't realize which method traced in those cases.
Could you tell me how can I generate new examples in same condition?

(And perhaps the information of "Which method was traced" should be appeared in the generated file.
I'll try on that topic in other PR.)

**Comment by yhirano55** [comment]
Ah...sorry, I don’t remember how to reproduce them.
